### ISSUE TITLE
dynamodb-seeder: Custom resource failed

### ISSUE THREAD

**Issue by ievgen-boink** [cloudcomponents/cdk-constructs#103]
Custom::DynamodbSeeder : Received response status [FAILED] from custom resource. Message returned: The provided key element does not match the schema

**Comment by hupe1980** [comment]
Does the test data match the table definition? **The provided key element does not match the schema**

**Comment by ievgen-boink** [comment]
Hey, thanks for the answer. Yes, i mentioned String and used number. Thanks a lot, i'll close this issue.
