### ISSUE TITLE
StaticSite support to root object in Cloudfront distribution to deploy Hugo, Gatsby and statically generated websites

### ISSUE THREAD

**Issue by danielesalvatore** [cloudcomponents/cdk-constructs#105]
We are trying to deploy a static website using the `StaticSite` construct.
When you host a Hugo website on S3 it functions perfectly but when you move it to CloudFront you likely get the nasty “AccessDenied” error. This is because the behavior of CloudFront’s default root object is quite different from the behavior of Amazon S3 index documents and how it deals with root objects. When you configure an Amazon S3 bucket as a website and specify the index document, Amazon S3 returns the index document even if a user requests a different subdirectory. This is absolutely not how CloudFront works thus you get the “AccessDenied” error.

We found out the following link is suggesting a possible solution [link](https://chrisschuld.com/2020/05/gatsby-hosting-on-cloudfront/) including an additional lambda at edge that includes the default root object to a subdirectory in case it is missing.

Would it be possible to include this feature in this library to enable the deployment of statically generated website (including Hugo, Gatsby, etc)?

Thank you very much in advance!

**Comment by matteoterrinoni** [comment]
+1
