### ISSUE TITLE
ContainerPort not working

### ISSUE THREAD

**Issue by cao2504** [cloudcomponents/cdk-constructs#106]
Hi, I'm trying to specify a container port but it seems like props is not working properly and keep default back to 80

```
Received response status [FAILED] from custom resource. Message returned: InvalidPar
ameterException: The container sample-website did not have a container port 80 defined.
```

```
const taskDefinition = new DummyTaskDefinition(this, 'DummyTaskDefinition', {
      image: 'nginx',
      family: this.props.family,
      containerPort: 8080,
    });
```

**Comment by fasatrix** [comment]
this should have been closed [here](https://github.com/cloudcomponents/cdk-constructs/pull/69), but it looks like it is not?

**Comment by hupe1980** [comment]
Did you change the port afterwards? The CustomResource currently does not support updates. It is only there to build the construct (Dummy). Then the taskdef is taken from the repo.

**Comment by cao2504** [comment]
so when are we supposed to pass the container port? we tried to create basic task definition using

```
const taskDefinition1 = new CustomResource(this, 'CustomResource', {
      serviceToken: 'shjsh',
      resourceType: 'Custom::DummyTaskDefinition',
      properties: {
        Family: this.props.family,
        Image: 'image',
        ExecutionRoleArn: 'ourArn',
        NetworkMode: NetworkMode.AWS_VPC,
        containerPort: 8080,
      },
    });
```
but then passing this into EcsService method we would get error about the type of the task definition is not a DummyTaskDefinition. Also it wouldn't make sense to do this way because what would be the point of using a Dummy one to start with. So We are a bit puzzled to where we are supposed to pass this in. We tried at the `CodeDeployEcsDeployAction` stage but there isn't such as property (containerPort)

**Comment by cao2504** [comment]
So the issue seems to happen only  when during the initial stack deployment( from scratch). If  we pass a custom containerPort 
 as prop to the DummyTaskDefinition, we get the following error message:
```
41/49 | 4:13:54 pm | CREATE_FAILED        | Custom::BlueGreenService                  | CdPipeline/EcsService/CustomResource/Default (CdPipelineEcsServiceCustomResourceB8D2C8AF) Received response status [FAILED] from custom resource. Message returned: InvalidParam
eterException: The container sample-website did not have a container port 80 defined.
```

however if the first deploy (1st scenario) uses a dummy task definition with the default container port (80)and we wait for an obvious failure (health check will fails our app runs on 8080 and target will never register) but then we perform a stack update where the dummy task definition uses container port as 8080 (2nd scenario) like the code in my initial post will work, everything works famously. How is that possible? Wouldn't be easier to permit a custom port directly in the DummyTaskDefinition?

See screenshots below First and Second scenario

Unhealthy first deploy
![image](https://user-images.githubusercontent.com/57603210/125561277-36c28233-674e-4ec4-b369-e6240fda05e9.png)
![image](https://user-images.githubusercontent.com/57603210/125561433-7b1dec19-18b1-4a5e-b0ae-57030bead041.png)


Healthy second deploy
![image](https://user-images.githubusercontent.com/57603210/125561157-f51a0739-63ec-429c-bbb2-eb4583d7c998.png)

**Comment by fasatrix** [comment]
@hupe1980 did you have a chance to take a look? Alternatively do you have examples where you first instanciate the DummyTaskDefinition without port(detaults to 80) and then pass the real task with a different image and port? I am very looking forward as the code that handles this part seems to be correct but hard to say without tests and/or examples. The behaviour mentioned by @cao2504  happens to me as well

**Comment by fasatrix** [comment]
@hupe1980 (or anyone else?). I am unable even to add logs to the container definition which should be a pretty straight forward and essential task while running container with ECS?  I get an error at codeDeploy level (`LogConfiguration.LogDriver `must not be blank- in fact it was not). 
This construct' behavior  appears to be unpredictable and at least an answer would be very much appreciated. Many thanks

**Comment by hupe1980** [comment]
Did you also set the port on the ECS service? I have now changed it so that as default the port is taken from the DummyTaskdef:

https://github.com/cloudcomponents/cdk-constructs/blob/70783b85be9e246eecba2133d3dfd32e47cc1191/packages/cdk-blue-green-container-deployment/src/ecs-service.ts#L45

**Comment by hupe1980** [comment]
@fasatrix Can you show your taskdef.json?

**Comment by fasatrix** [comment]
Hi @hupe1980 thanks for looking into this. This is the taskDef
```
{
  "cpu": "1024",
  "memory": "2048",
  "family": "family-BlueGreenCdStack",
  "networkMode": "awsvpc",
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "containerDefinitions": [
    {
      "essential": true,
      "cpu": 1024,
      "memory": 2048,
      "image": "<IMAGE1_NAME>",
      "portMappings": [
        {
          "hostPort": 8080,
          "protocol": "tcp",
          "containerPort": 8080
        }
      ],
      "environment": [],
      "secrets": [],
      "name": "my-app-name"
    }
  ]
}
```

**Comment by hupe1980** [comment]
@fasatrix What about the logConfiguration?

**Comment by cao2504** [comment]
@hupe1980 this is the logConfig I tried but it didnt not seem to apply to the container properly
```
containerDefinitions: [
        {
          logConfiguration: LogDriver.awsLogs({
            streamPrefix: 'BlueGreenCdStack',
          }),
]
```

**Comment by fasatrix** [comment]
@hupe1980 Thanks for the new version of the package. it seems to have fixed the issues. This can no be closed
