### ISSUE TITLE
Health check's grace period (as a Prop) for ECS service

### ISSUE THREAD

**Issue by fasatrix** [cloudcomponents/cdk-constructs#112]
Hi @hupe1980 ,
We are wondering how can we pass the the ECS's `healthCheckGracePeriodSeconds` to your library?

Thanks

**Comment by hupe1980** [comment]
Unfortunately the parameter is missing. I'm working on a fix right now

**Comment by fasatrix** [comment]
Thanks a lot for this much appreciated
