### ISSUE TITLE
Feature Request: Support DeploymentConfig creation

### ISSUE THREAD

**Issue by kimisme9386** [cloudcomponents/cdk-constructs#115]
The [cdk-blue-green-container-deployment](https://github.com/cloudcomponents/cdk-constructs/tree/master/packages/cdk-blue-green-container-deployment) CDK Construct is very handy to create Blue/Green deployment. But it doesn't support to create DeploymentConfig. It always use ALL_AT_ONCE. That’s a pity.

So I want to improve it for DeploymentConfig creation. Please let me know if the PR https://github.com/cloudcomponents/cdk-constructs/pull/114 has any problem, thanks.

@hupe1980

**Comment by hupe1980** [comment]
Yes, we should definitely support that. I commented on your PR
