### ISSUE TITLE
Add tagging Support for EcsService is blue-green cdk construct

### ISSUE THREAD

**Issue by aperuru** [cloudcomponents/cdk-constructs#132]
## **Issue:**
When using the cdk-blue-green-container-deployment, the resources created are not tagged and do not support tagging.

## **Solution:**
Allow the resources of the stack to be tagged properly via the parent stack, either by passing the tags directly to the resources to be handled by the custom resources lambda handler, to be used via the AwdSdkCall CDK class, or to be handled by the EcsService’s PropagateTags property.

**Comment by hupe1980** [comment]
Fixed with #141
