### ISSUE TITLE
Upgrade to aws cdk v2

### ISSUE THREAD

**Issue by hupe1980** [cloudcomponents/cdk-constructs#142]
AWS Cloud Development Kit (AWS CDK) v2 is now generally available:
- https://aws.amazon.com/about-aws/whats-new/2021/12/aws-cloud-development-kit-cdk-generally-available/

We have to update to use v2:
- https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-v2.html

**Comment by hupe1980** [comment]
@mbp Any help is welcome. So far I've only created the branch for the update.

**Comment by mrgum** [comment]
I'm looking at doing cdk-chatops and cdk-developer-tools-notifications. One question.

Do the versions of the packages (in package.json) all need upping to reflect the difference in using CDK v2?

How do we update all these while
- not breaking it for existing users allow them to stick to CDK v1
- allow future fixes/changes to the CDK v1 code (and let those using the CDK v2 version not revert to CDKv1 versions)

looking at https://github.com/cdklabs/cdk-nag/tree/v2-main they have are upping the versions so users request ^2.0.0 for CDK v2 and ^1.0.0 for CDK v1

so should I take @cloudcomponents/cdk-chatops version 1.50.0 and make a 2.50.0 that is the same as 1.50.0 but using CDK v2?

**Comment by hupe1980** [comment]
You don't have to worry about the version in package.json. When the migration is complete I will publish a new major release.

**Comment by caevv** [comment]
@hupe1980 can you create the new major versions (as beta)? Apparently, you have already migrated the package I need `@cloudcomponents/cdk-cloudfront-authorization`

**Comment by victorsibanda** [comment]
Hi @hupe1980, What is left to complete the migration to CDK_V2, would be happy to help with anything particular.

**Comment by hupe1980** [comment]
@victorsibanda You can see the progress in the cdk2 branch and in #142. Any help is welcome.
