### ISSUE TITLE
IS THIS PROJECT ALIVE ???

### ISSUE THREAD

**Issue by vasylherman** [cloudcomponents/cdk-constructs#199]
Hello,
I'd like to use constructs from this project. Don't see much is happening sine 2022.
Is this project ALIVE?

**Comment by kadishmal** [comment]
Apparently not, but I'm about to send a PR to updated Node.js from v12 to v18.

**Comment by zvictor** [comment]
> Apparently not, but I'm about to send a PR to updated Node.js from v12 to v18.

@kadishmal Your PR was the last one merged (#181). Coincidently, it had the same goal: updating nodejs.

**Comment by kadishmal** [comment]
Yes, go ahead. I’ve just got the permissions. Will review. Which version are you going to update?

**Comment by kadishmal** [comment]
@zvictor @PrettySolution, we've recently released an update to bump up the dependencies. Will close this issue. If there is any problem, just open the issue.
