### ISSUE TITLE
Enhanced Request for Support: Addressing the Deprecation of Node.js 14.x on AWS

### ISSUE THREAD

**Issue by Prasad-Telasula** [cloudcomponents/cdk-constructs#208]
AWS has discontinued support for nodejs14.x. This presents a significant issue for those of us relying on this runtime version. I am reaching out to inquire about the plans for upgrading to a newer, supported version of Node.js.

Could the team please provide an update regarding any ongoing development efforts aimed at addressing this compatibility issue? It is crucial for us to understand the timeline and scope of any forthcoming updates.

Thank you for your attention to this matter.

**Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: XXXX-db42-44e0-8580-XXX)" (RequestToken: XXXXXX-99a4-2c4d-ee02-XXXX, HandlerErrorCode: InvalidRequest)**

**Comment by Prasad-Telasula** [comment]
Code already supporting nodejs 18 with latest version

**Comment by kadishmal** [comment]
Correct, update to the latest v2 version, which includes Node v18 and v20 support with CDK v2 and AWS SDK v3.
