### ISSUE TITLE
IPV6 Support for Static Website

### ISSUE THREAD

**Issue by thekevinbrown** [cloudcomponents/cdk-constructs#28]
It'd be awesome if the StaticWebsite could also configure AAAA alias records here:

https://github.com/cloudcomponents/cdk-constructs/blob/master/packages/cdk-static-website/src/website-alias-record.ts

(I'd be happy to make a PR for this if it's desired behaviour.)

**Comment by hupe1980** [comment]
Yes we should support IPv6. You are welcome to create a PR

**Comment by thekevinbrown** [comment]
https://github.com/cloudcomponents/cdk-constructs/pull/31
