### ISSUE TITLE
Deploying to Static Website

### ISSUE THREAD

**Issue by thekevinbrown** [cloudcomponents/cdk-constructs#29]
It'd be awesome if passing in a source path to a directory also created a BucketDeployment so users can deploy to the static website along with creating it.

(I'd be happy to make a PR for this if it's desired behaviour.)

**Comment by hupe1980** [comment]
Did you try that?
```typescript
new StaticWebsite(this, 'StaticWebsite', {
        bucketConfiguration: {
                source: 'YOUR_PATH',
        }, 
...
}
```

**Comment by thekevinbrown** [comment]
Nope, didn't notice that, thanks!

I'll give it a go, and will let you know if I have any trouble.
