### ISSUE TITLE
Unable to send custom Role for Task definition 

### ISSUE THREAD

**Issue by niketh90** [cloudcomponents/cdk-constructs#40]
When using this cdk-blue-green-container-deployment plugin, For task definition it creates the roles by default. There should be a provision to supply own roles.

 const taskDefinition = new DummyTaskDefinition(
      this,
      'DummyTaskDefinition',
      {
        image: 'nginx',
        family: 'blue-green',
      },
**executionRole:**  
    );

**Comment by hupe1980** [comment]
Have you already tried this?
https://github.com/cloudcomponents/cdk-constructs/blob/82975a2cc622dd7ab370f1e95861473d39bcec71/packages/cdk-blue-green-container-deployment/src/dummy-task-definition.ts#L92-L97
