### ISSUE TITLE
[cdk-static-website] Allow skipping Route 53 records

### ISSUE THREAD

**Issue by hassankhan** [cloudcomponents/cdk-constructs#41]
Hi there,

Thanks so much for creating this project, really glad to see something like this exist 👍 

I was just wondering if the maintainers would be open to a new option in the [`cdk-static-website`](https://github.com/cloudcomponents/cdk-constructs/tree/master/packages/cdk-static-website) package that prevents Route 53 records from being created. This would be for scenarios where DNS is being handled externally (e.g. GoDaddy).

Happy to create a PR if there's interest

**Comment by hupe1980** [comment]
Yes of course. Feel free to create a pull request
