### ISSUE TITLE
DummyTaskDefinition container_port is ignored

### ISSUE THREAD

**Issue by kieranjen** [cloudcomponents/cdk-constructs#67]
Hi!

I am currently trying to set up an ECS blue/green deployment using your module (python).

I have noticed a potential issue when creating the dummy task definition. When running `cdk deploy` I get the following error:

`CREATE_FAILED        | Custom::BlueGreenService     | Service/CustomResource/Default (ServiceCustomResourceE0E93D09) Failed to create resource. InvalidParameterException: The container sample-website did not have a container port 8080 defined.`

It seems that the `container_port` attribute of `DummyTaskDefinition` is ignored.

Having reviewed the code it looks like it isn't outputted to the custom resource template that is created in CloudFormation and also isn't used in the lambda function that creates the dummy task definition.

If it helps you I can look into creating a pull request to fix this?

**Comment by hupe1980** [comment]
@kieranjen You are welcome to create a PR

**Comment by cao2504** [comment]
Hi, have this issue been resolved, I'm trying specify a container port but still get the error when I tried to deployed, it seems like it always go to port 80 somehow 
```
Received response status [FAILED] from custom resource. Message returned: InvalidPar
ameterException: The container sample-website did not have a container port 80 defined.
```
```
const taskDefinition = new DummyTaskDefinition(this, 'DummyTaskDefinition', {
      image: 'nginx',
      family: this.props.family,
      containerPort: 8080,
    });
```
