### ISSUE TITLE
Use the same Slack Chat with diferents pipelines

### ISSUE THREAD

**Issue by jizquierdo-tech** [cloudcomponents/cdk-constructs#92]
Hi,

I would like if it is possible to know how I can use the same Slack Channel with different stacks, currently, I received the next error:

Invalid request provided: Slack channel with ID XXXXXXXXX in Slack team XXXXXXXXX has already been configured for AWS account XXXXXXXXX. (Service: AWSChatbot; Status Code: 400; Error Code: InvalidRequestException; Request ID: XXXXXXXXX; Proxy: null)
--

**Comment by dhmw** [comment]
Hi,

This issue was closed without comment and is the only match when googling for this error message - did you find a solution?

Regards,
Doug.

**Comment by gio-trueper** [comment]
Having the same question almost a year later.

**Comment by RobertoPegoraro** [comment]
Does anyone know how solve it?

**Comment by peniqliotuv** [comment]
Ditto

**Comment by ragincajunbanjo** [comment]
I have run into this issue as well using terraform with awscc provider. Feel free to upvote that in the issues list... maybe we can all find a solution together.

**Comment by orekav** [comment]
I am having the same issue too

**Comment by cchubb-silvertree** [comment]
3.5 years later and I still can't have two pipelines notify the same slack channel?
