### ISSUE TITLE
Feature Request: Allow VPC declaration in PullRequestCheck

### ISSUE THREAD

**Issue by cardosi** [cloudcomponents/cdk-constructs#95]
First off - Thank you for all the work that has been done here, cdk-constructs is really cool and I think I'll get a lot of use out of it!

# Feature Request
I'd like to be able to pass an `iVPC` to `PullRequestCheck` so that the CodeBuild Project can run in a VPC. Here's AWS's documentation on [CodeBuild + VPCs](https://docs.aws.amazon.com/codebuild/latest/userguide/vpc-support.html) that has some use cases that may demonstrate why this would be useful (beyond my own).

I'm not very well versed in JS/TS (I've been using the Python implementation of CDK), but I went ahead and [created a PR](https://github.com/cloudcomponents/cdk-constructs/pull/94) anyway because it seemed like a pretty straight forward change. Hopefully it's helpful. #94

**Comment by hupe1980** [comment]
Closed with #94
